config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end

  root 'groups#index'

  resources :entities
  resources :group_entities
  resources :groups
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/group_entity.rb
class GroupEntity < ApplicationRecord
  belongs_to :group
  belongs_to :entity

  accepts_nested_attributes_for :entity
end

app/controllers/group_entities_controller.rb
# ApplicationController is the base controller class for your Rails application.
# It provides common functionality and acts as a parent class for other controllers.
class GroupEntitiesController < ApplicationController
  before_action :set_group_entity, only: %i[show edit update destroy]

  # GET /group_entities or /group_entities.json
  def index
    @group_entities = GroupEntity.all
  end

  # GET /group_entities/1 or /group_entities/1.json
  def show
    @group_entity = GroupEntity.find(params[:id])
    @group = Group.find(@group_entity.group_id)
    @entity = @group_entity.entity
  end

  # GET /group_entities/new
  def new
    @group_entity = GroupEntity.new
    @group = Group.find(params[:group_id])
    @group_entity.build_entity
    @groups = Group.all
    @group_id = params[:group_id]
  end

  # GET /group_entities/1/edit
  def edit
    @group_id = params[:group_id]
    @entity_id = params[:entity_id]
  end

  # POST /group_entities or /group_entities.json
  def create
    @group_entity = GroupEntity.new(group_entity_params)
    @groups = Group.all

    respond_to do |format|
      if @group_entity.save
        format.html do
          redirect_to group_path(@group_entity.group_id), notice: 'Group entity was successfully created.'
        end
        format.json { render :show, status: :created, location: @group_entity }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group_entity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /group_entities/1 or /group_entities/1.json
  def update
    respond_to do |format|
      if @group_entity.update(group_entity_params)
        format.html { redirect_to group_entity_url(@group_entity), notice: 'Group entity was successfully updated.' }
        format.json { render :show, status: :ok, location: @group_entity }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group_entity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /group_entities/1 or /group_entities/1.json
  def destroy
    @group_entity.destroy

    respond_to do |format|
      format.html { redirect_to group_entities_url, notice: 'Group entity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group_entity
    @group_entity = GroupEntity.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_entity_params
    params.require(:group_entity).permit(:group_id, entity_attributes: %i[id name amount]).tap do |whitelisted|
      whitelisted[:entity_attributes][:user_id] = current_user.id
    end
  end
end

app/views/group_entities/_form.html.erb
<%= form_with(model: @group_entity, url: group_entities_path, class: 'form-container') do |form| %>
  <% if @group_entity.errors.any? %>
    <div id="error_explanation" class="error-explanation">
      <h2><%= pluralize(@group_entity.errors.count, "error") %> prohibited this group_entity from being saved:</h2>

      <ul class="error-list">
        <% @group_entity.errors.full_messages.each do |message| %>
          <li class="error-message"><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.label :group_id, class: 'label' %>
  <%= form.collection_select :group_id, @groups, :id, :name, { prompt: 'Select Group' }, class: 'input-field' %>

  <%= form.fields_for :entity do |entity_form| %>
    <%= entity_form.label :name, class: 'label' %>
    <%= entity_form.text_field :name, class: 'input-field' %>

    <%= entity_form.label :amount, class: 'label' %>
    <%= entity_form.number_field :amount, class: 'input-field' %>
  <% end %>

  <%= form.submit 'Submit', class: 'submit-button' %>
<% end %>

app/views/group_entities/_group_entity.html.erb
<div id="<%= dom_id group_entity %>">
  <p>
    <strong>rendered</strong>
    
  </p>

</div>

app/views/group_entities/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Transactions</h1>

<div id="food_recipes">
  <% @group_entities.each do |group_entity| %>
    <%= render group_entity %>
    <p>
      <%= link_to "Show this transaction", group_entity %>
    </p>
  <% end %>
</div>

<%= link_to "Transaction", new_group_entity_path %>

app/views/group_entities/new.html.erb
<div class="container">
<h1>New Transaction</h1>

<%= render "form", group_entity: @group_entity %>

<br>

<div>
  <%= link_to "Back to transaction", group_path(@group_id), class: "link" %>
</div>
</div>

app/views/group_entities/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @group_entity %>

<div>
  <%= link_to "Edit this Transaction", edit_group_entity_path(@group_entity) %> |
  <%= link_to "Back to transactions", group_entities_path %>

  <%= button_to "Destroy this Transacation", @group_entity, method: :delete %>
</div>