config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end

  root 'groups#index'

  resources :entities
  resources :group_entities
  resources :groups
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :group_entities
  has_many :entities, through: :group_entities
end

app/controllers/groups_controller.rb
# ApplicationController is the base controller class for your Rails application.
# It provides common functionality and acts as a parent class for other controllers.
class GroupsController < ApplicationController
  before_action :set_group, only: %i[show edit update destroy]

  # GET /groups or /groups.json
  def index
    @groups = Group.all
    @group_entity_totals = {}

    @groups.each do |group|
      total_amount = 0

      group.group_entities.each do |group_entity|
        total_amount += group_entity.entity.amount
      end

      @group_entity_totals[group.id] = total_amount
    end
  end

  # GET /groups/1 or /groups/1.json
  def show
    @group = Group.find(params[:id])
    @group_entities = GroupEntity.where(group_id: @group.id).order(created_at: :desc)
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit; end

  # POST /groups or /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to group_url(@group), notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to group_url(@group), notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_params
    group = params.require(:group).permit(:name, :icon)
    group[:user_id] = current_user.id
    group
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_with(model: group) do |form| %>
  <% if group.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :icon, style: "display: block" %>
    <%= form.text_field :icon %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/groups/_group.html.erb
<div id="<%= dom_id group %>" class='group-flex'>
  <div class='icon-flex'>
  <div class='img-div'>
  <%= link_to(group, class: "img") do %>
    <%= image_tag(group.icon, class: "img-thumbnail", width: 85, height: 75) %>
  <% end %>
  </div>
 
  <div>
    <%= group.name %>
  </div>
  </div>
  <div>
    <p class='transaction-amt'>$<%= @group_entity_totals[group.id] %></p>
  </div>

</div>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render "form", group: @group %>

<br>

<div>
  <%= link_to "Show this group", @group %> |
  <%= link_to "Back to groups", groups_path %>
</div>

app/views/groups/index.html.erb
<div class="container">
  <p style="color: green"><%= notice %></p>

  <h1>Categories</h1>

  <div id="groups">
    <% @groups.each do |group| %>
      <div class="group-card">
      
        <%= render group %>
      </div>
    <% end %>
  </div>

  <%= link_to "Add Category", new_group_path, class: 'alink home-button' %>

</div>

app/views/groups/new.html.erb
<h1>New group</h1>

<%= render "form", group: @group %>

<br>

<div>
  <%= link_to "Back to groups", groups_path %>
</div>

app/views/groups/show.html.erb
<div class="contain">
  <p class="notice"><%= notice %></p>

  <h1 class="page-title">Transaction Page</h1>
  
  <% total_amount = 0 %>
  <% @group_entities.each do |group_entity| %>
  <% total_amount += group_entity.entity.amount %>
  <% end %>

  <div class="head-div">
  <p class='trans-heading'><%= @group.name %></p>
  <p class="transaction-amt">$ <%= total_amount %></p>
  </div>

  <ul class="group-entities-list">
    <% @group_entities.each do |group_entity| %>
      <li class="group-entity">
        <div> <p><%= group_entity.entity.name %><br><p></div>
        <div><p class='transaction-amt'>$ <%= group_entity.entity.amount %><br></p></div>
      </li>
    <% end %>
  </ul>

  
  <%= link_to "New Transaction", new_group_entity_path(group_id: @group.id), class: 'alink back-button' %>
  <%= link_to "Back", groups_path, class: 'link' %>
</div>
  